export const CAFE_ANALYSIS_2026 = {
  updatedAt: "25/09/2026",
  commercialBaseDate: "14/09/2026",
  drCutDate: "25/09/2026",
  overview: {
    mqls: 198,
    leads: 198,
    present: 85,
    absent: 113,
    presenceRate: 42.9,
    lost: 183,
    open: 11,
    won: 4,
    presentOpenOrWonRate: 12.9,
    absentOpenOrWonRate: 3.5,
    relativeOpenOrWonRatio: 3.7,
  },
  acquisition: {
    registeredTotal: 1303,
    mqlTotal: 198,
    conversionRate: 15.2,
    registrationsPerMql: 6.6,
    averageRegisteredPerCafe: 93.1,
    averageMqlPerCafe: 14.1,
    cafes: [
      ["Campinas", 102, 7],
      ["Fortaleza", 163, 24],
      ["Vitória", 85, 16],
      ["Cascavel", 66, 16],
      ["João Pessoa", 59, 26],
      ["Aracaju", 167, 13],
      ["Curitiba", 117, 7],
      ["Salvador", 110, 20],
      ["Uberlândia", 60, 11],
      ["São José do Rio Preto", 76, 17],
      ["Florianópolis", 124, 10],
      ["Manaus", 50, 7],
      ["Porto Alegre", 63, 17],
      ["Joinville", 61, 7],
    ],
  },
  cohorts: {
    present: {
      total: 85,
      lost: 74,
      open: 8,
      won: 3,
      lostRate: 87.1,
      openRate: 9.4,
      wonRate: 3.5,
      openOrWonRate: 12.9,
      wonAmongClosedRate: 3.9,
      advancedLosses: 20,
    },
    absent: {
      total: 113,
      lost: 109,
      open: 3,
      won: 1,
      lostRate: 96.5,
      openRate: 2.7,
      wonRate: 0.9,
      openOrWonRate: 3.5,
      wonAmongClosedRate: 0.9,
      advancedLosses: 16,
    },
  },
  cafes: [
    ["Campinas", 7, 2, 7, 0, 0],
    ["Fortaleza", 24, 8, 24, 0, 0],
    ["Vitória", 16, 9, 14, 0, 2],
    ["Cascavel", 16, 8, 15, 0, 1],
    ["João Pessoa", 26, 9, 26, 0, 0],
    ["Aracaju", 13, 6, 12, 1, 0],
    ["Curitiba", 7, 2, 7, 0, 0],
    ["Salvador", 20, 8, 19, 0, 1],
    ["Uberlândia", 11, 4, 11, 0, 0],
    ["São José do Rio Preto", 17, 10, 13, 4, 0],
    ["Florianópolis", 10, 4, 10, 0, 0],
    ["Manaus", 7, 4, 6, 1, 0],
    ["Porto Alegre", 17, 5, 14, 3, 0],
    ["Joinville", 7, 6, 5, 2, 0],
  ],
  dr: {
    total: 24,
    beforeTotal: 13,
    beforePresent: 5,
    beforeAbsent: 8,
    beforeRate: 38.5,
    afterTotal: 11,
    afterPresent: 6,
    afterAbsent: 5,
    afterRate: 54.5,
    totalPresent: 11,
    totalAbsent: 13,
    totalRate: 45.8,
    differencePoints: 16,
    cities: [
      ["Campinas", 3, 0],
      ["Fortaleza", 4, 2],
      ["Vitória", 2, 2],
      ["Cascavel", 1, 0],
      ["Uberlândia", 1, 1],
      ["Porto Alegre", 1, 0],
      ["São José dos Campos", 1, 0],
    ],
  },
  presentLosses: [
    ["Entrada", 1, [["Não possui obras/lançamentos dentro de 3 meses", 1]]],
    ["Prospecção 1", 14, [
      ["Empresa sem estrutura / Sem maturidade", 6],
      ["Não possui obras/lançamentos dentro de 3 meses", 3],
      ["Satisfeito com software atual", 2],
      ["Produto não atende", 2],
      ["Segmento não atendido", 1],
    ]],
    ["Prospecção 2", 33, [
      ["Tentativas de contato esgotadas", 27],
      ["Satisfeito com software atual", 3],
      ["Empresa sem estrutura / Sem maturidade", 1],
      ["Telefone incorreto ou não existe", 1],
      ["Pendência de informação / retorno", 1],
    ]],
    ["Agendamento", 6, [
      ["Tentativas de agendamento esgotadas", 4],
      ["Tentativas de contato esgotadas", 2],
    ]],
    ["Diagnóstico Realizado", 8, [
      ["Satisfeito com software atual", 4],
      ["Projeto adiado para mais de 3 meses", 2],
      ["Quebra de SLA de SQL", 1],
      ["Tempo de cadência", 1],
    ]],
    ["Maturação", 4, [
      ["Não consegui gerar valor", 1],
      ["Pendência de informação / retorno", 1],
      ["Empresa sem estrutura / Sem maturidade", 1],
      ["Não possui obras/lançamentos dentro de 3 meses", 1],
    ]],
    ["Negociação", 8, [
      ["Projeto adiado para mais de 3 meses", 2],
      ["Declinou por preço", 2],
      ["Não consegui gerar valor", 1],
      ["Sem cargo de decisão / influência", 1],
      ["Empresa sem estrutura / Sem maturidade", 1],
      ["Não possui obras/lançamentos dentro de 3 meses", 1],
    ]],
    ["Formalização", 0, [
      ["Nenhuma perda entre os participantes", 0],
      ["Participantes ganhos nesta etapa", 3],
    ]],
  ],
  absentLosses: [
    ["Entrada", 3, [
      ["Empresa sem estrutura / Sem maturidade", 1],
      ["Tentativas de contato esgotadas", 1],
      ["Segmento não atendido", 1],
    ]],
    ["Prospecção 1", 16, [
      ["Empresa sem estrutura / Sem maturidade", 7],
      ["Satisfeito com software atual", 3],
      ["Segmento não atendido", 3],
      ["Perdemos para concorrente", 1],
      ["Telefone incorreto ou não existe", 1],
      ["Sem verba/orçamento dentro de 3 meses", 1],
    ]],
    ["Prospecção 2", 68, [
      ["Tentativas de contato esgotadas", 58],
      ["Satisfeito com software atual", 6],
      ["Pendência de informação / retorno", 1],
      ["Não possui obras/lançamentos dentro de 3 meses", 1],
      ["Telefone incorreto ou não existe", 1],
      ["Empresa sem estrutura / Sem maturidade", 1],
    ]],
    ["Agendamento", 6, [
      ["Tentativas de contato esgotadas", 4],
      ["Tentativas de agendamento esgotadas", 1],
      ["Descarte automático via API", 1],
    ]],
    ["Diagnóstico Realizado", 12, [
      ["Pendência de informação / retorno", 3],
      ["Projeto adiado para mais de 3 meses", 2],
      ["Produto não atende", 1],
      ["Declinou por preço", 1],
      ["Tempo de cadência", 1],
      ["Sem cargo de decisão / influência", 1],
      ["Não consegui gerar valor", 1],
      ["Sem verba/orçamento dentro de 3 meses", 1],
      ["Satisfeito com software atual", 1],
    ]],
    ["Maturação", 2, [
      ["Satisfeito com software atual", 1],
      ["Sem verba/orçamento dentro de 3 meses", 1],
    ]],
    ["Negociação", 2, [
      ["Declinou por preço", 1],
      ["Projeto adiado para mais de 3 meses", 1],
    ]],
    ["Formalização", 0, [
      ["Nenhuma perda entre os não participantes", 0],
      ["Não participante ganho nesta etapa", 1],
    ]],
  ],
  reasonComparison: [
    ["Tentativas de contato esgotadas", 29, 63],
    ["Satisfeito com software atual", 9, 11],
    ["Empresa sem estrutura / Sem maturidade", 9, 9],
    ["Não possui obras/lançamentos dentro de 3 meses", 6, 1],
    ["Projeto adiado para mais de 3 meses", 4, 3],
    ["Tentativas de agendamento esgotadas", 4, 1],
    ["Pendência de informação / retorno", 2, 4],
    ["Segmento não atendido", 1, 4],
    ["Declinou por preço", 2, 2],
    ["Produto não atende", 2, 1],
    ["Sem verba/orçamento dentro de 3 meses", 0, 3],
    ["Telefone incorreto ou não existe", 1, 2],
    ["Não consegui gerar valor", 2, 1],
    ["Tempo de cadência", 1, 1],
    ["Sem cargo de decisão / influência", 1, 1],
    ["Quebra de SLA de SQL", 1, 0],
    ["Descarte automático via API", 0, 1],
    ["Perdemos para concorrente", 0, 1],
  ],
  openDeals: [
    ["Aracaju", "Laredo Urbanizadora Ltda", "Não", "Prospecção 2", 116],
    ["São José do Rio Preto", "Hugo Fabbri Incorporadora", "Sim", "Diagnóstico Realizado", 83],
    ["São José do Rio Preto", "Grupo Impper", "Sim", "Negociação", 83],
    ["São José do Rio Preto", "Settimo Engenharia de Construções Ltda", "Sim", "Diagnóstico Realizado", 83],
    ["São José do Rio Preto", "Tarraf", "Sim", "Diagnóstico Realizado", 83],
    ["Manaus", "FMZ Incorporadora", "Sim", "Diagnóstico Realizado", 59],
    ["Porto Alegre", "Concisa Construção e Incorporação Ltda", "Sim", "Prospecção 2", 27],
    ["Porto Alegre", "Magis Incorporadora", "Não", "Prospecção 2", 27],
    ["Porto Alegre", "FINKLER", "Não", "Entrada Parceiros", 27],
    ["Joinville", "ZR3 Empreendimentos", "Sim", "Diagnóstico Realizado", 25],
    ["Joinville", "Assis Estruturas", "Sim", "Diagnóstico Realizado", 25],
  ],
  wins: [
    ["Vitória", "WVS Construtora", "Sim", "Formalização", "Ganho"],
    ["Vitória", "Cinco Estrelas Construtora e Incorporadora", "Sim", "Formalização", "Ganho"],
    ["Salvador", "MBG Engenharia", "Sim", "Formalização", "Ganho"],
    ["Cascavel", "Ethos Engenharia Integrada", "Não", "Formalização", "Ganho"],
  ],
  lossTiming: {
    lostBeforeEvent: 14,
    presentDespitePriorLoss: 6,
    absentAndAlreadyLost: 8,
  },
  methodology: [
    "A planilha manual foi utilizada como fonte oficial para Café, lead e presença.",
    "A exportação do Pipe foi utilizada como fonte oficial para status, etapa atual ou última etapa, motivo de perda e data da perda.",
    "Os 40 registros não encontrados com segurança foram descartados completamente e não aparecem nos cálculos da base comercial.",
    "A base comercial contém 198 MQLs: 85 participantes e 113 não participantes.",
    "O estudo de DR é um recorte independente de 24 contas e inclui São José dos Campos.",
    "As comparações são descritivas: demonstram associações observadas, mas não determinam causalidade.",
    "Para negócios abertos, dias desde o Café não representa dias sem atividade.",
  ],
} as const;
